// gsap-react/src/App.js
import React, { useLayoutEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

export default function Scroll() {
  const main = useRef();

  useLayoutEffect(() => {
    const ctx = gsap.context((self) => {
      const boxes = self.selector('.box');
      boxes.forEach((box) => {
        gsap.to(box, {
          x: 150,
          scrollTrigger: {
            trigger: box,
            start: 'bottom bottom',
            end: 'top 20%',
            scrub: true,
          },
        });
      });
    }, main); // <- Scope!
    return () => ctx.revert(); // <- Cleanup!
  }, []);

  return (
    <div>
      <section className="section flex-center column">
        <h1>Basic ScrollTrigger with React</h1>
        <h2>Scroll down to see the magic happen!!</h2>
      </section>
      <div className="section flex-center column" ref={main}>
        <div className="box">box</div>
        <div className="box">box</div>
        <div className="box">box</div>
      </div>
      <section className="section"></section>
    </div>
  );
}

// gsap-svelte/src/App.svelte
<script>
	import { onMount } from 'svelte';
	import gsap from 'gsap';

	console.clear();

	let boxesContainer;

	onMount(() => {
		const ctx = gsap.context((self) => {
			const boxes = self.selector('.box');
			boxes.forEach((box) => {
				gsap.to(box, {
					x: 150,
					scrollTrigger: {
						trigger: box,
						start: 'bottom bottom',
						end: 'top 20%',
						scrub: true,
					}
				});
			});
		}, boxesContainer); // <- Scope!

		return () => ctx.revert(); // <- Cleanup!
	});
</script>

<div>
	<section class="section flex-center column">
		<h1>Basic ScrollTrigger with Svelte</h1>
		<h2>Scroll down to see the magic happen!!</h2>
	</section>
	<div class="section flex-center column" bind:this={boxesContainer}>
		<div class="box">box</div>
		<div class="box">box</div>
		<div class="box">box</div>
	</div>
	<section class="section" />
</div>
